FROM ubuntu:16.04

RUN apt-get update && \
    apt-get -y install python-dev \
    build-essential libssl-dev libffi-dev \
    libxml2-dev libxslt1-dev zlib1g-dev \
    python-pip

RUN pip install -U pymysql requests sqlalchemy celery

RUN useradd -ms /bin/bash web
USER web

WORKDIR /home/web
